# Configuration for nemi terminal emulator.

[log_settings]
enabled = true
output = <print>
include_callee = false
use_color = true
enable_info = true
enable_warnings = true
enable_errors = true


[scripts]
vmode=./scripts/vmode.pl

[asdasdasd]
bruh = true
