[MAIN_SETTINGS]
shell = /bin/bash
padding_x = 10.0
padding_y = 10.0
line_padding = 3.0
vsync = true
soft_blink = true
soft_blink_pow = 1.0
blink_speed = 9.0
show_frametime = false
hide_mouse = false

# If this is set to something you
# have installed, you can open files with it from scripts.
favourite_texteditor = vim

# This is the directory where the source code for Nemi is.
# Set empty if you dont need it.
source_dir = .
recompile_num_cores = 8
